### ISSUE TITLE
Getting Attribute Error

### ISSUE THREAD

**Issue by aareman** [blb-ventures/strawberry-django-plus#1]
Working on migrating from graphene and django over to strawberry and django. Very excited about this plugin as it looks like it really enhances the strawberry+django world. So far experience very positive, running into one issue so far.

![image](https://user-images.githubusercontent.com/10500823/150218798-bb3e2e94-c2ff-4962-af79-35a979645241.png)
![image](https://user-images.githubusercontent.com/10500823/150218872-d567e0c7-3fdd-4308-bf0d-cc6d7acce2d6.png)

schema is federated
![image](https://user-images.githubusercontent.com/10500823/150218904-f92af541-aedf-433e-ac8a-acac0040fca9.png)

# Note

- using sync views
- using federation
- This error only occurs during testing (with pytest) the live version of the query works fine

Thank you!

**Comment by bellini666** [comment]
Hey @aareman .

First of all, thanks for the positive feedback! :)

Regarding the issue. It seems that no `context` was provided to the execution context. The `GraphQLView` from the django integration provides an object that has `.request` and `.response` in it, and the extension adds its configuration to it so it can be retrieved inside resolvers.

Since pytest is calling the schema directly, no context was provided. One thing you could do is to provide the context at the execute_query like:

```python
from django.http import HttpRequest, HttpResponse
from strawberry.django.context import StrawberryDjangoContext

schema.execute_async(
    query,
    context_value=StrawberryDjangoContext(request=HttpRequest(), response=HttpResponse(),
)
```

Actually, even if you did `context=value=object()` would work, because the extension just needs something to force set its config in it, and any object would do, but doing the above would be the closest that the django view does.

**Comment by aareman** [comment]
Thank you @bellini666 for the fast response! All working now.

**Comment by bellini666** [comment]
Awesome! :)

Going to close the issue now. Looking forward for more feedback and issue reports if you have any
