### ISSUE TITLE
Optimizier omits slicing of connection query set

### ISSUE THREAD

**Issue by oleo65** [blb-ventures/strawberry-django-plus#143]
I have been trying to figure out why some of my queries are painfully slow. This happens when I traverse a reverse foreign key relation through django related managers. 

In my query I limit the number of instances `LeafModel` to be fetched to a small number (e.g. one) because the list might be huge. The query returns the requested data just fine but takes a *long* time to complete.

Having inspected the issued SQL statements, the `OFFSET` and `LIMIT` SQL statements for the related `LeafModel` instances are missing. I suspect that somewhere during query optimization the slicing of the related model is *lost*. During execution *all* instances of `LeafModel` are fetched and then sliced on python side not in the database which makes the query magnitudes slower and inefficient.

Consider this minimal example:

```python
# models.py

class LeafModel(models.Model):
    property = models.TextField()

class SourceModel(models.Model):
    leaf_model = models.ForeignKey(LeafModel, models.CASCADE)
```

```python
# schema.py

@gql.django.type(LeafModel)
class LeafModelNode(gql.relay.Node):
    property: str

@gql.django.type(SourceModel)
class SourceModelNode(gql.relay.Node):

    @gql.django.connection(disable_optimization=False)
    def leaf_models(self, info: Info) -> gql.relay.Connection[LazyType["LeafModelNode", "graphql_api.schema.models.leaf_model"]]:
        return self.leaf_model_set

@gql.type
class Query:
    source_models: gql.relay.Connection[SourceModelNode] = gql.django.connection()
```

```gql
{
  sourceModel(first: 1) {
    edges {
      node {
        leafModels(last: 1) {
          edges {
            node {
              property
            }
          }
        }
      }
    }
  }
}
```

Is this something which is simply not possible? Am I missing some configuration or customizing here? Coming from `graphene` a few months back the exakt same query was running fine and performant with their implementation of reverse foreign key traversal.

I suspect the `_get_model_hints` function in the `optimizer.py` module... https://github.com/blb-ventures/strawberry-django-plus/blob/87fb0948f8ae9158a0884d21221a8ad7abf2a436/strawberry_django_plus/optimizer.py#L72

Any help is much appreciated. 😃

**Comment by bellini666** [comment]
Hi @oleo65 ,

I have not fully implemented/tested nested connections, but we can use this issue to track this.

One things that worries me here is basically how the nested connection works in terms of optimization. For example, if you have a `List` inside a connection it is not a problem to `prefetch_related` them, because you want to return the list of objects for each node inside the connection. But if you have a connection, doing a complete `prefetch_related` on them means you would be loading a lot of objects that would be sliced after (and that can mean _a lot_ of objects, which can cause memory issues).

How can we overcome this issue in a nice way? How did graphene behaved in this case? Although I used graphene before, I have never had a nested connection use case in my projects

**Comment by moritz89** [comment]
To add to the requirements, it would be useful to be able to use the same filtering / ordering parameters as on the base query. Extending the above example:

```
@gql.django.filter(LeafModel, lookups=True)
class LeafModelFilter:
    property: gql.auto

@gql.django.order(LeafModel)
class LeafModelOrder:
    property: gql.auto

@gql.django.type(LeafModel, filters=LeafModelFilter, order=LeafModelOrder)
class LeafModelNode(gql.relay.Node):
    property: str
```

I'd expect to be able to filter and order the nested node as follows:

```
{ sourceModel(first: 1) { edges { node {
    leafModels(last: 1, order: {property: DESC}, filters: {property: {startsWith: "foo"}})
        { edges { node { property } } }
} } } }
```
