### ISSUE TITLE
Relay connection does not work with async

### ISSUE THREAD

**Issue by pcraciunoiu** [blb-ventures/strawberry-django-plus#196]
Thanks for writing this and adding relay support!

Unit tests were hanging when testing async with relay connections. There's no async support in the `from_nodes` method which calls the Django ORM.

**Comment by pcraciunoiu** [comment]
Here is a WIP PR that gets async to work, but I'm pretty sure it breaks sync:
https://github.com/blb-ventures/strawberry-django-plus/pull/197

I'd appreciate some pointers as to how to make it work both sync and async.

**Comment by bellini666** [comment]
Hey @pcraciunoiu ,

I'm contributing thr relay integration to strawberry in [this PR](https://github.com/strawberry-graphql/strawberry/pull/2511/files#diff-87ff2a77ed8a7dc2eb7fc8a320e55d457b77160ab7932c185b8becbf8662767bR712), and after it is merged there it will be more powerful than the current version in here. In there the `from_nodes` method does support async iterators/generators

Having said that, what exactly are you trying to do that has an async iterator?

If you want to iterate over a django queryset asynchronously, using `gql.django.connection` will wrap the `from_nodes` in `sync_to_async` and call it asynchronously (which is something that can be removed once we can use the integration from the PR I mentioned)

If it is something else, can you give me an example so I can better understand the issue and give you some pointers?

**Comment by pcraciunoiu** [comment]
> Having said that, what exactly are you trying to do that has an async iterator?

@bellini666 data loaders are async only - https://strawberry.rocks/docs/guides/dataloaders

That's how I ran into this.

If you can suggest how to make data loaders work without these changes that'd be great. I haven't looked into the PR you linked in detail, but I don't see any async keywords.

If it's close to getting merged, I could wait and try to switch to strawberry's Relay connection instead of using the strawberry-django-plus Relay connection.

**Comment by pcraciunoiu** [comment]
To clarify. Running ASGI requests breaks the relay connection method that the PR addresses. It doesn't have to also use data loaders, but data loaders are the reason I switched to async.

**Comment by bellini666** [comment]
> If you can suggest how to make data loaders work without these changes that'd be great. I haven't looked into the PR you linked in detail, but I don't see any async keywords.

You can see it here: https://github.com/strawberry-graphql/strawberry/pull/2511/files#diff-87ff2a77ed8a7dc2eb7fc8a320e55d457b77160ab7932c185b8becbf8662767bR806 . That code handles both sync and async

But based on what you wrote, if I understood it correctly, loading the nodes from a dataloader to paginate them?


> To clarify. Running ASGI requests breaks the relay connection method that the PR addresses. It doesn't have to also use data loaders, but data loaders are the reason I switched to async.

I use this lib in some ASGI projects, all of them make extensively use of connections, async resolvers and dataloders.

Could you try to share an example of what you are trying to do and what is happening? Just so that I can properly understand your issue and guide you better (or discover a possible issue and find a way to fix/workaround it)

**Comment by pcraciunoiu** [comment]
@bellini666 so are you suggesting to switch to use this once it's merged? Is it pretty close? I am thinking to use my fork and once this is merged switch to the `strawberry` relay instead of `strawberry_django_plus` relay.

I didn't do anything fancy, just tried to set up dataloaders with relay pagination, and as you can see if you query for `totalCount`, it's using `.count()` which would not work in async context. Have you ever used the `strawberry_django_plus` relay with pagination and query for `totalCount` in async, and did it work? Maybe I'm doing something wrong but I didn't customize anything that I can think of.

**Comment by bellini666** [comment]
@pcraciunoiu that's why I'm asking for an example, because I'm not really understanding the relation between dataloaders and the connection here.

What happens here is that for django connections the whole `from_nodes` is called from a `sync_to_async` context, meaning that doing `.count()` and even iterating over the queryset will work correctly. The new version in strawberry has some differences to this which will need to be adapted later, specially for `totalCount`

**Comment by pcraciunoiu** [comment]
@bellini666 Thanks for the follow-up. There is no relation with data loaders, sorry for the confusion. I just use async because of them.

So with that said, when using async with Django runserver, for me the `from_nodes` was not getting called from `sync_to_async`. I finally put together an example so you can see, even the base implementation doesn't work. I don't think I'm doing anything special, but if it works for you maybe I screwed something up in the setup.

```
You cannot call this from an async context - use a thread or sync_to_async.

GraphQL request:2:5
1 | query Article {
2 |     articles {
  |     ^
3 |         totalCount
Traceback (most recent call last):
  File "/home/paul/Uplift/Projects/Uplift/uplift-core/.venv/lib/python3.11/site-packages/graphql/execution/execute.py", line 528, in await_result
    return_type, field_nodes, info, path, await result
                                          ^^^^^^^^^^^^
  File "/home/paul/Uplift/Projects/Uplift/uplift-core/.venv/lib/python3.11/site-packages/strawberry/schema/schema_converter.py", line 570, in _async_resolver
    return await await_maybe(
           ^^^^^^^^^^^^^^^^^^
  File "/home/paul/Uplift/Projects/Uplift/uplift-core/.venv/lib/python3.11/site-packages/strawberry/utils/await_maybe.py", line 12, in await_maybe
    return await value
           ^^^^^^^^^^^
  File "/home/paul/Uplift/Projects/Uplift/uplift-core/.venv/lib/python3.11/site-packages/strawberry_django_plus/utils/aio.py", line 89, in resolve_async
    ret = resolver(await value)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/paul/Uplift/Projects/Uplift/uplift-core/.venv/lib/python3.11/site-packages/strawberry_django_plus/relay.py", line 1053, in <lambda>
    lambda resolved: self.resolver(
                     ^^^^^^^^^^^^^^
  File "/home/paul/Uplift/Projects/Uplift/uplift-core/.venv/lib/python3.11/site-packages/strawberry_django_plus/relay.py", line 1065, in resolver
    return self.resolve_connection(cast(Iterable[Node], nodes), info, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paul/Uplift/Projects/Uplift/uplift-core/.venv/lib/python3.11/site-packages/strawberry_django_plus/relay.py", line 1074, in resolve_connection
    return return_type.from_nodes(nodes, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paul/Uplift/Projects/Uplift/uplift-core/.venv/lib/python3.11/site-packages/strawberry_django_plus/relay.py", line 688, in from_nodes
    total_count = int(nodes.count())  # type: ignore

```

The view is just a `AsyncGraphQLView` subclass.

Resolver:

```python
    @relay.connection
    async def articles(self) -> Iterable[Article]:
        return models.Article.all_objects.all()
```

Query:

```graphql
query Article {
    articles {
        totalCount
        edges {
            node {
                id
                title
            }
        }
    }
}
```

**Comment by bellini666** [comment]
Hey @pcraciunoiu,

Based on that snipped, the issue is exactly what I replied in my first comment.

For django you need to use `gql.django.connection` instead of `relay.connection. Try this:

```python
    @gql.django.connection
    async def articles(self) -> Iterable[Article]:
        return models.Article.all_objects.all()
```

The difference is that it will [this field](https://github.com/blb-ventures/strawberry-django-plus/blob/main/strawberry_django_plus/field.py#L311) instead of the `ConnectionField`, which does 2 things:

1) Ensures that `resolve_connection` is handled correctly in async contexts (your case)
2) Make sure `order` and `filters` are correctly added to arguments if the type/field defines them

**Comment by pcraciunoiu** [comment]
Thank you, switching to that field works. I was using `gql.relay.connection` instead of `gql.django.connection`. Didn't realize the former doesn't work in this case.

Really appreciate the help!
