### ISSUE TITLE
Support standard property fields

### ISSUE THREAD

**Issue by SafaAlFulaijLumofy** [blb-ventures/strawberry-django-plus#198]
Using `@property` fields raises this line:
https://github.com/blb-ventures/strawberry-django-plus/blob/af55c4c3681a4c1de95fd64c512a02aa14a344fb/strawberry_django_plus/type.py#L167

Many times we need to keep using normal property fields, and instead add the optimization hints to the schema field.

This also breaks other libraries like https://github.com/W1ldPo1nter/django-queryable-properties
Example use: (`is_alpha` field)  (https://django-queryable-properties.readthedocs.io/en/stable/common.html):
```python
class ApplicationVersion(models.Model):
    ALPHA = 'a'
    BETA = 'b'
    STABLE = 's'
    RELEASE_TYPE_CHOICES = (
        (ALPHA, _('Alpha')),
        (BETA, _('Beta')),
        (STABLE, _('Stable')),
    )

    release_type = models.CharField(max_length=1, choices=RELEASE_TYPE_CHOICES)

    objects = QueryablePropertiesManager()

    is_alpha = ValueCheckProperty('release_type', ALPHA)
```

**Comment by bellini666** [comment]
Hey @SafaAlFulaijLumofy ,

This happens when using properties with `auto`? I think it should be worth adding support for properties as long as they are annotated.

Currently you can use [@model_property](https://blb-ventures.github.io/strawberry-django-plus/query-optimizer/#model-property), which is also integrated with the optimizer.

I didn't know django-queryable-properties, it seems an awesome lib and solves a similar problem that I tried to solve using `model_property`, but with more features. I'll try to add an integration for it as well :)

**Comment by bellini666** [comment]
@SafaAlFulaijLumofy I just released a new version that should support `@property`

I checked django-queryable-properties and its property is a subclass of `property`, so it should work out-of-the-box for you. Please tell me if it is not the case
