### ISSUE TITLE
Private fields not present in resolvers

### ISSUE THREAD

**Issue by moritz89** [blb-ventures/strawberry-django-plus#208]
It seems to be the case that private fields are not accessible in resolver fields. I did not find anything in strawberry-django-plus specific docs or examples, only in the [base docs](https://strawberry.rocks/docs/types/private). Am I missing something? The workaround is really simple, but would like to know if this is a supported use case?

Code bellow is a simplified version of an actual use case.

```py
from strawberry.scalars import JSON
from strawberry_django_plus.gql import relay
from strawberry_django_plus import gql

@gql.django.type(SomeModel)
class SomeModelNode(relay.Node):
    PRIVATE_DATA: gql.Private[dict] = {"foo": 1, "bar": 2}

    @gql.django.field
    def data(self, root: SomeModel) -> JSON:
        data_out = {}
        for k, v in self.PRIVATE_DATA.items():
            data_out[k] = v + 1
        return data_out
```

**Comment by moritz89** [comment]
Found a proper solution, although the approach does not mirror how the examples are written. In the case of the `data(...)`method, `self` and `root` refer to the same object (checked via `id(...)`). In order to access the class attributes of SomeModelNode, the method has to be specified as a class method. This results in the first parameter in `data(...)` being the actual class and `root` being the Django model instance (`SomeModel` in this case).

Therefore what works is, only not sure if this is all intended behavior :sweat_smile: 

```py
@gql.django.type(SomeModel)
class SomeModelNode(relay.Node):
    PRIVATE_DATA = {"foo": 1, "bar": 2}

    @gql.django.field
    @classmethod
    def data(cls, root: SomeModel) -> JSON:
        data_out = {}
        for k, v in cls.PRIVATE_DATA.items():
            data_out[k] = v + 1
        return data_out

```

**Comment by bellini666** [comment]
Hey @moritz89 ,

This is actually what strawberry does: https://strawberry.rocks/docs/types/resolvers#defining-resolvers-as-methods

Usually `self`/`root` will be the object of the type itself, but in case of django, it will be the django model and the type acts as an "interface" for it (i.e. if the type as a `foo` attribute, any object that can resolve `getattr(obj, 'foo')` will work, which is the case for the django model), but unfortunately that means you can't actually access the type object itself (because it doesn't exist), other than doing what you did with a `classmethod`
