### ISSUE TITLE
Self is None in input_mutation methods

### ISSUE THREAD

**Issue by moritz89** [blb-ventures/strawberry-django-plus#221]
Don't know if this is by design, but `self` in input_mutation methods is None:

```py
@gql.type
class Mutation:
    @gql.django.input_mutation
    def create_controller(self, info: Info, ...) -> ControllerType:
        assert self == None
        ...

    def _helper_method(...):
        ...
```

The background is that it would be useful to have methods in the same class to simplify the main mutation method. A workaround is to simply create standalone methods. Are there any other approaches?

**Comment by bellini666** [comment]
Hey @moritz89 ,

Yeah, it is by design of strawberry itself: https://strawberry.rocks/docs/types/resolvers#defining-resolvers-as-methods

Mutation resolvers are the same as query resolvers, and `self` corresponds to the `root` value of that mutation. For root types, like `Query` and `Mutation` those will be `None`.

If I'm not mistaken, you can use classmethods on both `create_controller` and `_helper_method` to workaround that. But the easier solution would be to define `_helper_method` outside of the class

**Comment by moritz89** [comment]
Thanks!
