### ISSUE TITLE
Is this project here to stay?

### ISSUE THREAD

**Issue by nrbnlulu** [blb-ventures/strawberry-django-plus#24]
Sorry for the question but with the current state of Django-graphql community in python its is a very reasonable question
i.e [graphene](https://github.com/graphql-python/graphene), 
 [graphql_auth](https://github.com/pedrobern/django-graphql-auth/) ,
[graphene-django](https://github.com/graphql-python/graphene),

**Comment by bellini666** [comment]
Hey @nrbnlulu ,

I'm not sure what is happening with the graphene community at the moment. It seems to me that graphene itself is being deprecated, but there are some people that wants to keep maintaining it. Only time will tell...

Now, strawberry has a totally different community, which is not very active but growing a lot from time to time. I personally think that it is going to be the status quo of graphql servers in python very soon.

Regarding this lib, it has some enhancements over the official integration, mostly for use cases that I have on my company's projects. They were all graphene-based before, and now I'm migrating all of them to strawberry. So I don't plan on abandoning this project because I rely a lot on it.

Having said all of that, I recently became a strawberry core developer and am currently planning on merging some of the functionality/fixes from this lib to the official one, which I'm also going to be maintaining there. In the future this lib will contain only some special functionality, while some of its core (e.g. the query optimizer) will be merged there.

Does this answer your question?

**Comment by nrbnlulu** [comment]
Hi, thanks for the detailed answer.
It seems that i will need either to migrate from graphene to strawberry or REST.

Thanks!
