### ISSUE TITLE
input_mutation: TypeError: MutateContentInput fields cannot be resolved

### ISSUE THREAD

**Issue by devkral** [blb-ventures/strawberry-django-plus#242]
Somehow input field types are lost. "content" is of type strawberry.input.
See: secretgraph/schema/mutations/update.py of https://github.com/secretgraph/secretgraph

File "./secretgraph/secretgraph/schema.py", line 26, in <module>
    schema = Schema(
             ^^^^^^^
  File "./secretgraph/.venv/lib/python3.11/site-packages/graphene_protector/strawberry.py", line 66, in __init__
    super().__init__(*args, **kwargs)
  File "./secretgraph/.venv/lib/python3.11/site-packages/strawberry/schema/schema.py", line 159, in __init__
    raise error.__cause__ from None
  File "./secretgraph/.venv/lib/python3.11/site-packages/graphql/type/definition.py", line 1456, in fields
    fields = resolve_thunk(self._fields)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./secretgraph/.venv/lib/python3.11/site-packages/graphql/type/definition.py", line 300, in resolve_thunk
    return thunk() if callable(thunk) else thunk
           ^^^^^^^
  File "./secretgraph/.venv/lib/python3.11/site-packages/strawberry/schema/schema_converter.py", line 378, in <lambda>
    fields=lambda: self.get_graphql_input_fields(type_definition),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./secretgraph/.venv/lib/python3.11/site-packages/strawberry/schema/schema_converter.py", line 353, in get_graphql_input_fields
    return self._get_thunk_mapping(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "./secretgraph/.venv/lib/python3.11/site-packages/strawberry/schema/schema_converter.py", line 334, in _get_thunk_mapping
    raise UnresolvedFieldTypeError(type_definition, field)
strawberry.exceptions.unresolved_field_type.UnresolvedFieldTypeError: Could not resolve the type of 'content'. Check that the class is accessible from the global module scope.

**Comment by bellini666** [comment]
Hey @devkral ,

Is that issue happening with the v3 release?

Could you provide me a step by step on how to reproduce that traceback using your project?

**Comment by devkral** [comment]
Steps to reproduce
- setup secretgraph (cloning repo and create it with poetry install)
- ./manage.py export_schema (here happens the crash)

**Comment by bellini666** [comment]
@devkral 

Hrm, I could reproduce the issue in your repo, but I'm not really sure what is happening there. It seems that the argument is loosing its namespace in the `StrawberryAnnotation`, but I don't know what is causing it. Maybe it is some weird interaction based on the fact that you do some kind of nested mutation resolving (first time seeing something like this =P).

Also, the input mutation is now using the strawberry's `InputMutationExtension`, so I think the issue is probably there.

Could you try to create a minimal contained reproduction example for this? It would be nice to test if the minimal reproduction example happens only with strawberry-django-plus or if it does happen when when using the [InputMutationExtension](https://strawberry.rocks/docs/general/mutations#the-input-mutation-extension) directly.

**Comment by devkral** [comment]
thanks for the hint, did test it against InputMutationExtension. it fails with only
``` python
 updateOrCreateContent: ContentMutation = gql.mutation(
        resolver=mutate_content,
        extensions=[InputMutationExtension()],
        handle_django_errors=False,
    )
```
for a poc just remove all input_mutation except one in the `secretgraph/server/schema/schema.py`.

**Comment by devkral** [comment]
I think it is a bug in InputMutationExtension

**Comment by devkral** [comment]
It could be related to:
https://github.com/strawberry-graphql/strawberry/issues/2864

**Comment by bellini666** [comment]
@devkral oh, that's nice! I'll take a look at it soon to try to understand what might be going on

**Comment by devkral** [comment]
fixed (PR merged and tests don't fail anymore).
