### ISSUE TITLE
[add() / set()] got an unexpected keyword argument 'bulk'"

### ISSUE THREAD

**Issue by darwinhace** [blb-ventures/strawberry-django-plus#6]
When I'm using set() or add() on ManyToManyRel, mutation always throws errors, when I check resolver on update_m2m there is argument 'bulk' append to function add() or set() when using ManyToManyRel, I think ManyToManyField and ManyTo ManyRel doesn't recognize bulk argument.

> Using add() with a many-to-many relationship, however, will not call any save() methods (the bulk argument doesn’t exist), but rather create the relationships using [QuerySet.bulk_create()](https://docs.djangoproject.com/en/4.0/ref/models/querysets/#django.db.models.query.QuerySet.bulk_create). If you need to execute some custom logic when a relationship is created, listen to the [m2m_changed](https://docs.djangoproject.com/en/4.0/ref/signals/#django.db.models.signals.m2m_changed) signal, which will trigger pre_add and post_add actions.

**Comment by bellini666** [comment]
Hey @darwinhace . Should be fixed in the next release that I'm doing right now. Please tell me if it is really fixed or not.

**Comment by darwinhace** [comment]
thank you @bellini666, and congrats for releasing v1.0 :partying_face:

**Comment by bellini666** [comment]
Hahah thanks! :)

After covering pratically 90% of the code with tests and having the basic functionality that I considered to be the MVP of the lib, I thought it was the perfect momento for the 1.0 release.

More features will come through and this is still a young project, so keep posting your issues here because they help me a lot!
