### ISSUE TITLE
Ask for feature: pass down the `kwargs` to the `check_condition` method

### ISSUE THREAD

**Issue by ammar-faifi** [blb-ventures/strawberry-django-plus#70]
## The Problem
As many devs who moved on from the `graphene` based libs, I found this lib provides me with what  I want.
 But one thing I miss, I cannot modify or check the `input` type before it goes to be executed in the Django ORM.

## The simple solution
the implemented directive here is just amazing. To check whether a user owns an object, I subclassed the `ConditionDiretive`:
```python
@dataclasses.dataclass
class OwnsObjPerm(ConditionDirective):

    message: Private[str] = "You don't have such object."

    def check_condition(
        self, root: Any, info: GraphQLResolveInfo, user: UserType, **kwargs
    ):
        pk = info.variable_values["pk"]  # get object `pk`
        if models.Evaluation.objects.filter(pk=pk, user=user).exists():
            return True

        return False
```

it worked. but the dict `info.variable_values` contains only the variables that have been sent through `"variables"` POST. This means, variables hard coded in the query cannot be accessed. 
another problem, changing a value in `info.variable_values` won't affect the queryset  execution.

to solve those problems I passed the `kwargs` from `resolve` of the directive down to the  `check_condition` method as the above snippet.
I added `kwargs` after this line
https://github.com/blb-ventures/strawberry-django-plus/blob/ab74f5ed96e7343c63160bcbeade0d333abe16c8/strawberry_django_plus/permissions.py#L263

So wonder if we can do this modification.

## Alternative Solution
or we can extend the idea of directives and create a custom directive, like
```python 
@dataclasses.dataclass
class CustomDirective(SchemaDirectiveWithResolver):
    """Base auth directive definition."""

    has_resolver: ClassVar = True

    def resolve(
        self,
        helper: SchemaDirectiveHelper,
        _next: Callable,
        root: Any,
        info: GraphQLResolveInfo,
        *args,
        **kwargs,
    ):
        print(kwargs)
        resolver = functools.partial(_next, root, info, *args, **kwargs)


        if callable(resolver):
            resolver = resolver()
        return resolver
```
but for sure I broke down the async stuff.

so is it possible to implement an easy-to-use custom directive class, that devs can just subclass it out of box?

**Comment by bellini666** [comment]
Hi @ammar-faifi ,

I don't see a problem in passing `*args`/`**kwargs` down to the resolver.

The whole permissioned directives think is basically a set of fancy middlewares =P. The `AuthDirective` basically retrieves the user and calls `resolve_for_user`, which subclasses must implement. When I implemented it I didn't pass `*args`/`**kwargs` because I didn't think that they would be useful. If I understood you issue correctly, by changing `resolve_for_user` and `check_condition` to receive those, you should be able to only have to implement your own directive and only have to worry about overriding `check_condition`, and everything will be there for you.

It should be a straightforward change. Do you want to try to open a PR for it? I'll gladly review it and make a new release once it is merged!

**Comment by ammar-faifi** [comment]
yes I'd love. in fact, I did this change and it works just fine, I will open PR soon
