### ISSUE TITLE
Merge to strawberry / strawberry-django

### ISSUE THREAD

**Issue by nrbnlulu** [blb-ventures/strawberry-django-plus#73]
Hello @bellini666, I am willing to help with the process of  merging this repo to strawberry and i have some suggestions / questions.
1.could you provide list of the features that are divided to what to contribute to strawberry what  to strawberry-django and what should stay here?
2. do you have any plan on how to do this? 
3. I want to create a site for the documentation. [I am familiar ](https://nrbnlulu.github.io/strawberry-django-auth/index)with mkdocs served by  gh-pages  what are your thoughts? Also, should they live inside the main strawberry site or should they be in sole strawberry-django site? 
4. should we save the current API or prefer the strawberry-django API?
5. any other things I should know before I dive into this?

**Comment by bellini666** [comment]
Hey @nrbnlulu ,

> 1.could you provide list of the features that are divided to what to contribute to strawberry what to strawberry-django and what should stay here?

Your issue just made me create this issue on `strawberry-graphql-django`: https://github.com/strawberry-graphql/strawberry-graphql-django/issues/139 :)

> 2. do you have any plan on how to do this?

I was actually planning on doing that myself once I had some spare time, but I haven't got any yet in the last days unfortunately. I'm planning to start working on this probably by the end of the month if everything goes well though!

But since the issues there are now opened, any help with the migration process is really nice! Since most of the work here is based on `strawberry-graphql-django`, some of the porting should be a matter of replacing `strawberry-graphql-django`'s implementation by the one here (in cases where we have an optimized version of the implementation), or merging both implementations, or just porting the whole module (e.g. the optimizer) directly and adding some tests for those there.

> 3. I want to create a site for the documentation. [I am familiar ](https://nrbnlulu.github.io/strawberry-django-auth/index)with mkdocs served by gh-pages what are your thoughts? Also, should they live inside the main strawberry site or should they be in sole strawberry-django site?

Based on the fact that most of the work in this repo is probably going to be merged in `strawberry-graphql-django`, it would probably be really nice to document them in its existing [doc infrastructure](https://github.com/strawberry-graphql/strawberry-graphql-django/tree/main/docs) during the migration process.

Obviously, feel free to contribute documentation back to this project, which in the end can also be ported together to there as well :)

> 4. should we save the current API or prefer the strawberry-django API?

What do you mean here?

> 5. any other things I should know before I dive into this?

Probably the issue that I opened on `strawberry-graphql-django` will help to understand what needs to be done, and is also a good place to discuss the "not so obvious things to migrate" (or in their own issues).

But feel free to hit me here or on discord if you need any help with anything :)

**Comment by nrbnlulu** [comment]
> What do you mean here?
i.e 
- `from strawberry.django import gql` or `from strawberry.django import whatever`
- `gql.create_mutation` or `strawberry.django.mutations.create`
I guess it is not one answer for all but you get the concept..

**Comment by bellini666** [comment]
> > What do you mean here?
> 
> i.e:
> 
> * `from strawberry.django import gql` or `from strawberry.django import whatever`
> * `gql.create_mutation` or `strawberry.django.mutations.create`
> 
> I guess it is not one answer for all but you get the concept..

Oh I see. I created the `gql` shortcut because this lib's name is very long, and it is not exposed on `strawberry`'s namespace to be used like the django's integration as `strawberry.django.type` for example.

We should keep its defaults there.

**Comment by bellini666** [comment]
Fixed in https://github.com/strawberry-graphql/strawberry-graphql-django/releases/tag/v0.10.0 :)
