### ISSUE TITLE
Ordering order being ignored

### ISSUE THREAD

**Issue by Kitefiko** [blb-ventures/strawberry-django-plus#88]
Hi,
when ordering with 2 and more values order of values is bound to the definition of Order object thus negating user defined order.

Am I mistaken in assuming these two should not be equivalent? (demo project)
```
query {
  milestoneList(
    order: {
      project: {
        name: ASC
      }
      name: ASC
    }
  ) {
    name
    project {
      name
    }
  }
}
```
```
query {
  milestoneList(
    order: {
      name: ASC
      project: {
        name: ASC
      }
    }
  ) {
    name
    project {
      name
    }
  }
}
```

The result of both of these queries is the same seems like the actual order is determined via schema definition and not input?

**Comment by bellini666** [comment]
Hi @Kitefiko ,

That behaviour is inherited from https://github.com/strawberry-graphql/strawberry-graphql-django, this lib doesn't do anything different with it.

Would you mind opening an issue there?

I think we probably will need to create a new ordering implementation, which uses lists instead of an object, which would allow the order to be respected.
