### ISSUE TITLE
How to hook into build in mutations

### ISSUE THREAD

**Issue by oleo65** [blb-ventures/strawberry-django-plus#96]
I have been struggling to build an efficient mutation pattern around the provided create/update/delete mutations without repeating tremendous amounts of code. After hours of debugging and trying to understand the magic of dataclasses, typing, etc. I think it might not possible to build upon the provided mutations.

Consider this (classes are shortened):

```python
@gql.django.type(Asset)
class AssetNode(ModelNode):
    equity: EquityNode | None
    buy_price: gql.auto

@gql.django.partial(Asset)
class UpdateAssetInput(gql.NodeInput):
    equity: gql.auto
    buy_price: gql.auto

@gql.type
class AssetMutation:

    @gql.mutation
    @login_required
    def update_asset(self, info: Info, input: UpdateAssetInput) -> AssetNode:
        _asset: Asset = Asset.objects.get(pk=input.id.node_id)
        if _asset.owner == info.context.request.user:
            field: AssetNode = gql.django.update_mutation(UpdateAssetInput)
            result = field.get_result(None, info, None, kwargs={'input': input})
            return result

        raise PermissionError("You can only modify objects you own.")
```

I need a server side validation that the provided `ModelID` is owned by the user of the current context. The validation runs fine, the `update_mutation` field is created properly, but calling `field.get_result` failes because somehow the model property does not get populated. There seems to be some issue with typing annotations but I cannot get my head around it.

Is this a use case maybe not possible with the library at the moment? Is there any recommendation on how to implement this?

I tried going down the path with directives but they run "too early" and don't have access to the actual model instance for validation.

Side notes:

There are some issues with the code above in respect to performance.

* The model instance is fetched twice from the database. Once during owner checking and once during update.
* Typing seems to be off. Field is acually not an `AssetNode` but a `DjangoUpdateMutationField`

Thanks for your support. 😃

**Comment by bellini666** [comment]
Hi @oleo65 ,

Please correct if I'm understanding this wrong ok?

From what I understand, you want to reuse the update logic with custom behaviour, is that right? If so, you should be implementing something similar to what `DjangoUpdateMutationField` does.

In you case, probably this:

```python
from strawberry_django_plus.mutations import resolvers


@gql.type
class AssetMutation:
    @gql.mutation
    @login_required
    def update_asset(self, info: Info, input: UpdateAssetInput) -> AssetNode:
        data = vars(input)
        pk = data.pop("id")
        _asset = pk.resolve_node(info, ensure_type=Asset)
        if _asset.owner != info.context.request.user:
            raise PermissionError("You can only modify objects you own.")

        return resolvers.update(info, _asset, resolvers.parse_input(info, data))
```

The main change here is to parse the input and use `resolvers.update`, which already returns the object itself to be resolved by the return fields.

I took the liberty of also suggesting 2 improvements there:

1) Use `resolve_node` to retrieve the node itself. You can also do this like you were doing, but resolve_node will also ensure that the type part of the id is correct (meaning that if someone passes `FooBarType:1` instead of `AssertType:1` it will raise an error instead of simply retrieving the asset of id 1

2) I like to have the early returns for errors and corner cases, so that the main code follows the smallest indentation path. Just a suggestion since I changed the whole if clause =P

> The model instance is fetched twice from the database. Once during owner checking and once during update.

This might be because of the way you were doing things, by calling the field again. Please try to use what I suggested and tell me if you still get duplicated queries.

> Typing seems to be off. Field is acually not an AssetNode but a DjangoUpdateMutationField

Same! :)

**Comment by oleo65** [comment]
You are a genius 😃 

It is working as expected. I was looking for a hook too far up in the call chain as I thought I might loose all the neat features as directives, filters, etc if using the resolvers directly.

But they have to be configured on `field` level which now is my `update_asset` with `@gql.mutation`.

The queries are sorted out as well and no duplicate queries for the model instance are issued. 🎉 

Thanks for your code suggestions. I am always eager to learn something new. 

Side Note: Could / Should we maybe leave a hint at the docs on how to customize the mutations or where to hook into as a best practice? Maybe at least with a link to this issue? So the next person looking for something similar will find it more easily. What's your thoughts on docs. If you think this is something worth adding I am happy to write up a pull request.

**Comment by bellini666** [comment]
Awesome! :)

> Side Note: Could / Should we maybe leave a hint at the docs on how to customize the mutations or where to hook into as a best practice? Maybe at least with a link to this issue? So the next person looking for something similar will find it more easily. What's your thoughts on docs. If you think this is something worth adding I am happy to write up a pull request.

Sure! Feel free to open a PR to improve the docs and I'll gladly review and merge it :). There's a lot to improve in the docs to be honest, I'm not very good when it comes to documentation =P

**Comment by bellini666** [comment]
Btw, since this is basically solved I'm going to close ok?
